const db = {
    wallpapers:[
        {
            name:'lantern.jpg',
            category:'art',
        },
        {
            name:'nature.jpg',
            category:'nature',
        },
        {
            name:'sky.jpg',
            category:'space',
        },
        {
            name:'space.jpg',
            category:'space',
        },
        {
            name:'apple.JPG',
            category:'art',
        },
        {
            name:'art.jpg',
            category:'art',
        },
        {
            name:'rain.jpg',
            category:'rain',
        },
        {
            name:'nature2.jpg',
            category:'nature',
        },
        {
            name:'art2.JPG',
            category:'art',
        },
        {
            name:'art3.jpg',
            category:'art',
        },
    ],
    categories:['space','nature','art'],
}

export default db;